
'''
print("How to use:")
print("")
print("")
print("Left Click to start creating a contour\ndraw the points where ever you want")
print("  and then to close the contour Right Click and the code will automatically start")
print("  displaying its predicted color + its index in the contours array")
print("")
print("")
print("Right click on a contour to Enable or Disable reporting of the dominant colors inside it")
print("  that is being displayed inside the color ranges window (disignated by half height white boxes")
print("  drawn always on the red color bar)")
print("  (disabled contours are colored green and enabled contours are colored black)")
print("")
print("")
print("Right click away from all contours to start a reordering process where you can Left Click all of the")
print("  contours sequentially to put them in the order you want inside the contours array in order to code")
print("  relative to the array's indexes, once you have selected all of the contours right click again away from")
print("  any contour and the new order will be applied")
print("  (selected contours will be colored green during selection)")
print("")
print("")
print("The color range selection GUI is split vertically onto three parts, H and S and V and each line")
print("  contains the value for each of the six colors")
print("  each color has two knobs that you can drag left and right to adjust the limits (except for red ")
print("  it has four knobs in order to adjust two ranges because that seems to work better")
print("")
print("")
print("Everything is saved inside pickle files in the project directory")
'''